In [2]:
import numpy as np
print('hello world ')

hello world 


In [3]:
myarr= np.array([3,4,56,7],np.int8)#int8 number should not be big
myarr
myarr[0]
#if any value is too big then show an error

np.int8(3)

In [4]:
myarr= np.array([[3,4,56,7]])
myarr[0,1]

np.int64(4)

In [5]:
myarr.dtype
myarr.shape

(1, 4)

In [6]:
myarr[0,1]=45
myarr

array([[ 3, 45, 56,  7]])

In [52]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

print("a1D =\n", a1D)
print("a2D =\n", a2D)
print("a3D =\n", a3D)

a1D =
 [1 2 3 4]
a2D =
 [[1 2]
 [3 4]]
a3D =
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
##arry creation :conversion from other Python structure

In [9]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray
listarray.dtype
listarray.shape
listarray.size

9

In [10]:
listarray.shape
listarray
np.array({34,23,89})

array({89, 34, 23}, dtype=object)

In [11]:
zeros=np.zeros((2,6))#creating array
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
rng=np.arange(6)#ceating a numpy array in 5
rng

array([0, 1, 2, 3, 4, 5])

In [13]:
lspace=np.linspace(1,5,12)
lspace
#here it gives us 12 randomly floating elements which is 
# start at 1 and end at 5 with same space location 


array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [14]:
lspace=np.linspace(1,5,5)#list 
lspace

array([1., 2., 3., 4., 5.])

In [15]:
emp=np.empty((4,3))
emp
#create a matrix 

array([[1.        , 1.36363636, 1.72727273],
       [2.09090909, 2.45454545, 2.81818182],
       [3.18181818, 3.54545455, 3.90909091],
       [4.27272727, 4.63636364, 5.        ]])

In [16]:
emp_like=np.empty_like((4,5))
emp_like

array([1321235094032,             0])

In [17]:
ide=np.identity(45)
ide #if i want a big array

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [18]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [19]:
arr.reshape(3,33)#32 elements each list 
#arange is 99 so it full fill the value 99 
#if we input small or big range it show an error 
#it not like the 99 value same 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [20]:
arr.ravel()#create a 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [21]:
arr.shape#1D array it has 99 element is 

(99,)

In [22]:
x=[[1,2,3],[4,5,6],[4,4,5]]
x#it will print as a array
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [4, 4, 5]])

In [23]:
ar.sum(axis=0)#it will sum all the column

array([ 9, 11, 14])

In [24]:
ar.sum(axis=1)#it will  sum all the row

array([ 6, 15, 13])

In [25]:
ar.T#transpose te ar array /matrix 
#row covert in column and column will convert in row


array([[1, 4, 4],
       [2, 5, 4],
       [3, 6, 5]])

In [26]:
ar.flat

In [27]:
for item in ar.flat:#all item will show
    print(item)

1
2
3
4
5
6
4
4
5


In [28]:
ar.ndim#number of dimension is 2 here 
# so it show 2 here 

2

In [29]:
ar.size

9

In [30]:
ar.nbytes# my array elements how much space will consume it show it

72

In [31]:
one =np.array ([1,2,3,4,5,6])
one.argmax()#wher the maximum number of index in return it

np.int64(5)

In [32]:
one.argmin()#where the minimum number of index it return it


np.int64(0)

In [33]:
one.argsort()#small to big short

array([0, 1, 2, 3, 4, 5])

In [34]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [4, 4, 5]])

In [35]:
ar.argmin()

np.int64(0)

In [36]:
ar.argmax()

np.int64(5)

In [37]:
ar.argmax(axis=0)#column maximum value it show


array([1, 1, 1])

In [38]:
ar.argmax(axis=1)

array([2, 2, 2])

In [39]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [40]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 4, 4, 5])

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [4, 4, 5]])

In [42]:
ar2=np.array([[1,2,1],[6,8,8],[1,2,3]])
ar2

array([[1, 2, 1],
       [6, 8, 8],
       [1, 2, 3]])

In [43]:
ar+ar2

array([[ 2,  4,  4],
       [10, 13, 14],
       [ 5,  6,  8]])

In [44]:
ar*ar2

array([[ 1,  4,  3],
       [24, 40, 48],
       [ 4,  8, 15]])

In [45]:
ar.sum()

np.int64(34)

In [46]:
ar.max()

np.int64(6)

In [47]:
np.where(ar>5)#in ar matrix array where getter than is 5 element then show it

(array([1]), array([2]))

In [48]:
#print non zero value 
np.count_nonzero(ar)#9 element of non zero 

np.int64(9)

In [49]:
import sys
py_ar=[0,45,67]
np_ar= np.array(py_ar)
sys.getsizeof(1)*len(py_ar)#totall space of this numpy array

84

In [50]:
np_ar.itemsize*np_ar.size

24